# project.yml (at the ROOT of the repository)

name: ASimplePurchaseKitProject

options:
  bundleIdPrefix: io.appsimple
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    DEVELOPMENT_TEAM: 3E5665FPU5
    CODE_SIGN_STYLE: Automatic

packages:
  ASimplePurchaseKit: # local Swift package
    path: .
  
targets:
  TestHostAppTarget:
    type: application
    platform: iOS
    sources:
      - path: PurchaseKitTestHarness/PurchaseKitTestHarness
    info:
      path: PurchaseKitTestHarness/PurchaseKitTestHarness/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.appsimple.TestHostApp
        PRODUCT_NAME: TestHostApp
    dependencies:
      - package: ASimplePurchaseKit   # dependency on the local package
        product: ASimplePurchaseKit # TestHostApp depends on the package product
    resources:
      - path: PurchaseKitTestHarness/Tests/Products.storekit

  TestHostAppTestsTarget:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: PurchaseKitTestHarness/Tests
    resources: 
      - path: PurchaseKitTestHarness/Tests/Products.storekit          
      - path: PurchaseKitTestHarness/Tests/TestLifetimeOnly.storekit 
      - path: PurchaseKitTestHarness/Tests/TestSubscriptionOnly.storekit
      - path: PurchaseKitTestHarness/Tests/TestMinimalSubscription.storekit
    info:
      path: PurchaseKitTestHarness/Tests/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.appsimple.TestHostApp.Tests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/TestHostApp.app/TestHostApp
        BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: TestHostAppTarget
      - sdk: StoreKit.framework

  ASimplePurchaseKitTestsTarget:
    type: bundle.unit-test
    platform: iOS
    sources: [] # no sources needed – tests come from SwiftPM
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.appsimple.ASimplePurchaseKitTests
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/TestHostApp.app/TestHostApp
        BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: TestHostAppTarget
      - sdk: StoreKit.framework
      - package: ASimplePurchaseKit

schemes:
  TestHostAppScheme:
    build:
      targets:
        TestHostAppTarget: all
        TestHostAppTestsTarget: testing
    test:
      targets:
        - TestHostAppTestsTarget
  ASimplePurchaseKit-UnitTestsScheme:
    build:
      targets:
        TestHostAppTarget: all
        ASimplePurchaseKitTestsTarget: all # ensure app (and therefore package code) is built
      test:
        targets:
          - target: ASimplePurchaseKitTests  # This is the name of your .testTarget in Package.swift
            hostTarget: TestHostAppTarget   # Explicitly set the host application for these tests
            # skipped: false (default)
        # If you use a common StoreKit configuration for these tests:
        storeKitConfiguration: PurchaseKitTestHarness/Tests/Products.storekit
        # Ensure the configuration matches what your tests expect.
        # config: Debug # (If you need to specify a build configuration for testing)